---
- name: Instalacion de NGINX desde repositorios oficiales 
  hosts: all
  become: yes 
  tasks:

    - name: Instalar requisitos previos
      apt:
        name:
          - curl
          - gnupg2
          - ca-certificates
          - lsb-release
          - debian-archive-keyring
        state: present
        update_cache: yes

    - name: Descargar clave de firma oficial NGINX
      ansible.builtin.get_url:
        url: https://nginx.org/keys/nginx_signing.key
        dest: /tmp/nginx_signing.key
        mode: '0644'

    - name: Convertir clave a formato GPG y guardar keyring
      shell: |
        gpg --dearmor < /tmp/nginx_signing.key > /usr/share/keyrings/nginx-archive-keyring.gpg 
      args:
        creates: /usr/share/keyrings/nginx-archive-keyring.gpg 

    - name: Verificar clave descargada
      shell: |
        gpg --dry-run --quiet --no-keyring --import --import-options import-show /usr/share/keyrings/nginx-archive-keyring.gpg
      register: gpg_check_output
      changed_when: false

    - name: Configurar repositorio apt para paquetes NGINX estables 
      copy: 
        dest: /etc/apt/sources.list.d/nginx.list
        content:
          deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/debian {{ ansible_lsb.codename }} nginx

    - name: Actualizar cache de paquetes 
      apt: 
        update_cache: yes

    - name: Instalar NGINX
      apt:
        name: nginx
        state: present